### ISSUE TITLE
Yices 2.6 released

### ISSUE THREAD

**Issue by josalhor** [pysmt/yicespy#3]
Hi,

Currently, yicespy supports yices 2.5.2. However, the last version since 2018-06-30 is the 2.6 version.

I can't currently check if everything works with the new version as it did with the previous one. If it does the Readme should be updated.

Josep

**Comment by marcogario** [comment]
I updated the version of yices is pysmt, and ran all tests successfully. You should be able to use 2.6.0. Please let me know if you experience any issue. I will update the Readme.

https://github.com/pysmt/pysmt/pull/509
